languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Maintec Entertainment"
copyright = "[John Main Designs ©](mailto:info@themains2.org)"

[params]
  description = "Premium DJ services for Weddings, Community Socials, and Graduation Dances in Ethelbert and across Manitoba. Making your events unforgettable."
  dateFormat = "2 January 2006"


[params.author]
  # name = "John Main"
  # image = "img/author.jpg"
  # headline = "I'm only human"
  # bio = "A little bit about you"
  links = [
    { facebook = "https://www.facebook.com/MaintecEntertainment/" }
  ]
