[[main]]
  identifier = "services"
  name = "Services"
  url = "/#services"
  weight = 10

[[main]]
  identifier = "karaoke"
  name = "Karaoke"
  url = "/karaoke/"
  weight = 20

[[main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 25

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 30
