baseURL = 'https://entertainment.themains.org/'
locale = 'en-us'
title = 'DJ & Karaoke Services in Ethelbert & Parkland, MB | Maintec Entertainment'
disableLanguages = ["id"]

[author]
  name = "John Main"
